language: cpp
os:
  - linux
  - osx
compiler:
  - g++
  - clang++
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - zlib1g-dev 
    - libboost-all-dev 
    - libssl-dev
before_script:
    - uname -a
    - printenv
    - which clang++
    - clang++ --version 2>&1 | grep clang
    - which g++
    - g++ --version
    - $CXX --version
    - pwd
script:
    - pwd
    - cd Release
    - mkdir build.debug
    - cd build.debug
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - make
    - cd Binaries
    - ./test_runner *_test.so
notifications:
  email:
    recipients: yuriy.solodkyy+travis.cpprestsdk@gmail.com
    on_success: change
    on_failure: always
