var searchData=
[
  ['task',['task',['../classpplx_1_1task.html',1,'pplx']]],
  ['task_3c_20details_3a_3a_5funit_5ftype_20_3e',['task&lt; details::_Unit_type &gt;',['../classpplx_1_1task.html',1,'pplx']]],
  ['task_3c_20void_20_3e',['task&lt; void &gt;',['../classpplx_1_1task_3_01void_01_4.html',1,'pplx']]],
  ['task_5fcanceled',['task_canceled',['../classpplx_1_1task__canceled.html',1,'pplx']]],
  ['task_5fcompletion_5fevent',['task_completion_event',['../classpplx_1_1task__completion__event.html',1,'pplx']]],
  ['task_5fcompletion_5fevent_3c_20details_3a_3a_5funit_5ftype_20_3e',['task_completion_event&lt; details::_Unit_type &gt;',['../classpplx_1_1task__completion__event.html',1,'pplx']]],
  ['task_5fcompletion_5fevent_3c_20int_5ftype_20_3e',['task_completion_event&lt; int_type &gt;',['../classpplx_1_1task__completion__event.html',1,'pplx']]],
  ['task_5fcompletion_5fevent_3c_20resulttype_20_3e',['task_completion_event&lt; ResultType &gt;',['../classpplx_1_1task__completion__event.html',1,'pplx']]],
  ['task_5fcompletion_5fevent_3c_20size_5ft_20_3e',['task_completion_event&lt; size_t &gt;',['../classpplx_1_1task__completion__event.html',1,'pplx']]],
  ['task_5fcompletion_5fevent_3c_20std_3a_3ashared_5fptr_3c_20concurrency_3a_3astreams_3a_3adetails_3a_3abasic_5fstreambuf_3c_20_5fchartype_20_3e_20_3e_20_3e',['task_completion_event&lt; std::shared_ptr&lt; Concurrency::streams::details::basic_streambuf&lt; _CharType &gt; &gt; &gt;',['../classpplx_1_1task__completion__event.html',1,'pplx']]],
  ['task_5fcompletion_5fevent_3c_20utility_3a_3asize64_5ft_20_3e',['task_completion_event&lt; utility::size64_t &gt;',['../classpplx_1_1task__completion__event.html',1,'pplx']]],
  ['task_5fcompletion_5fevent_3c_20void_20_3e',['task_completion_event&lt; void &gt;',['../classpplx_1_1task__completion__event_3_01void_01_4.html',1,'pplx']]],
  ['task_5fcompletion_5fevent_3c_20web_3a_3ahttp_3a_3ahttp_5fresponse_20_3e',['task_completion_event&lt; web::http::http_response &gt;',['../classpplx_1_1task__completion__event.html',1,'pplx']]],
  ['task_5fcontinuation_5fcontext',['task_continuation_context',['../classpplx_1_1task__continuation__context.html',1,'pplx']]],
  ['task_5foptions',['task_options',['../classpplx_1_1task__options.html',1,'pplx']]],
  ['threadpool',['threadpool',['../classcrossplat_1_1threadpool.html',1,'crossplat']]],
  ['tokenregistrationcontainer',['TokenRegistrationContainer',['../classpplx_1_1details_1_1___cancellation_token_state_1_1_token_registration_container.html',1,'pplx::details::_CancellationTokenState']]],
  ['type_5fparser',['type_parser',['../class_concurrency_1_1streams_1_1type__parser.html',1,'Concurrency::streams']]],
  ['type_5fparser_3c_20chartype_2c_20bool_20_3e',['type_parser&lt; CharType, bool &gt;',['../class_concurrency_1_1streams_1_1type__parser_3_01_char_type_00_01bool_01_4.html',1,'Concurrency::streams']]],
  ['type_5fparser_3c_20chartype_2c_20char_20_3e',['type_parser&lt; CharType, char &gt;',['../class_concurrency_1_1streams_1_1type__parser_3_01_char_type_00_01char_01_4.html',1,'Concurrency::streams']]],
  ['type_5fparser_3c_20chartype_2c_20double_20_3e',['type_parser&lt; CharType, double &gt;',['../class_concurrency_1_1streams_1_1type__parser_3_01_char_type_00_01double_01_4.html',1,'Concurrency::streams']]],
  ['type_5fparser_3c_20chartype_2c_20float_20_3e',['type_parser&lt; CharType, float &gt;',['../class_concurrency_1_1streams_1_1type__parser_3_01_char_type_00_01float_01_4.html',1,'Concurrency::streams']]],
  ['type_5fparser_3c_20chartype_2c_20int64_5ft_20_3e',['type_parser&lt; CharType, int64_t &gt;',['../class_concurrency_1_1streams_1_1type__parser_3_01_char_type_00_01int64__t_01_4.html',1,'Concurrency::streams']]],
  ['type_5fparser_3c_20chartype_2c_20signed_20char_20_3e',['type_parser&lt; CharType, signed char &gt;',['../class_concurrency_1_1streams_1_1type__parser_3_01_char_type_00_01signed_01char_01_4.html',1,'Concurrency::streams']]],
  ['type_5fparser_3c_20chartype_2c_20std_3a_3abasic_5fstring_3c_20chartype_20_3e_20_3e',['type_parser&lt; CharType, std::basic_string&lt; CharType &gt; &gt;',['../class_concurrency_1_1streams_1_1type__parser_3_01_char_type_00_01std_1_1basic__string_3_01_char_type_01_4_01_4.html',1,'Concurrency::streams']]],
  ['type_5fparser_3c_20chartype_2c_20uint64_5ft_20_3e',['type_parser&lt; CharType, uint64_t &gt;',['../class_concurrency_1_1streams_1_1type__parser_3_01_char_type_00_01uint64__t_01_4.html',1,'Concurrency::streams']]],
  ['type_5fparser_3c_20chartype_2c_20unsigned_20char_20_3e',['type_parser&lt; CharType, unsigned char &gt;',['../class_concurrency_1_1streams_1_1type__parser_3_01_char_type_00_01unsigned_01char_01_4.html',1,'Concurrency::streams']]]
];
