var searchData=
[
  ['_5farray',['_Array',['../classweb_1_1json_1_1details_1_1___array.html',1,'web::json::details']]],
  ['_5fautodeleter',['_AutoDeleter',['../structpplx_1_1details_1_1___auto_deleter.html',1,'pplx::details']]],
  ['_5fbadargtype',['_BadArgType',['../structpplx_1_1details_1_1___bad_arg_type.html',1,'pplx::details']]],
  ['_5fbadcontinuationparamtype',['_BadContinuationParamType',['../structpplx_1_1details_1_1___bad_continuation_param_type.html',1,'pplx::details']]],
  ['_5fboolean',['_Boolean',['../classweb_1_1json_1_1details_1_1___boolean.html',1,'web::json::details']]],
  ['_5fcancellationtokencallback',['_CancellationTokenCallback',['../classpplx_1_1details_1_1___cancellation_token_callback.html',1,'pplx::details']]],
  ['_5fcancellationtokenregistration',['_CancellationTokenRegistration',['../classpplx_1_1details_1_1___cancellation_token_registration.html',1,'pplx::details']]],
  ['_5fcancellationtokenstate',['_CancellationTokenState',['../classpplx_1_1details_1_1___cancellation_token_state.html',1,'pplx::details']]],
  ['_5fcase_5finsensitive_5fcmp',['_case_insensitive_cmp',['../structweb_1_1http_1_1http__headers_1_1__case__insensitive__cmp.html',1,'web::http::http_headers']]],
  ['_5fcontextcallback',['_ContextCallback',['../classpplx_1_1details_1_1___context_callback.html',1,'pplx::details']]],
  ['_5fcontinuation_5ffunc_5ftransformer',['_Continuation_func_transformer',['../classpplx_1_1___continuation__func__transformer.html',1,'pplx']]],
  ['_5fcontinuation_5ffunc_5ftransformer_3c_20_5fintype_2c_20void_20_3e',['_Continuation_func_transformer&lt; _InType, void &gt;',['../classpplx_1_1___continuation__func__transformer_3_01___in_type_00_01void_01_4.html',1,'pplx']]],
  ['_5fcontinuation_5ffunc_5ftransformer_3c_20void_2c_20_5fouttype_20_3e',['_Continuation_func_transformer&lt; void, _OutType &gt;',['../classpplx_1_1___continuation__func__transformer_3_01void_00_01___out_type_01_4.html',1,'pplx']]],
  ['_5fcontinuation_5ffunc_5ftransformer_3c_20void_2c_20void_20_3e',['_Continuation_func_transformer&lt; void, void &gt;',['../classpplx_1_1___continuation__func__transformer_3_01void_00_01void_01_4.html',1,'pplx']]],
  ['_5fcontinuationtaskhandlebase',['_ContinuationTaskHandleBase',['../structpplx_1_1details_1_1___continuation_task_handle_base.html',1,'pplx::details']]],
  ['_5fcontinuationtypetraits',['_ContinuationTypeTraits',['../structpplx_1_1details_1_1___continuation_type_traits.html',1,'pplx::details']]],
  ['_5fdouble_5fstate',['_double_state',['../struct_concurrency_1_1streams_1_1__double__state.html',1,'Concurrency::streams']]],
  ['_5fexceptionholder',['_ExceptionHolder',['../structpplx_1_1details_1_1___exception_holder.html',1,'pplx::details']]],
  ['_5ffile_5finfo',['_file_info',['../struct_concurrency_1_1streams_1_1details_1_1__file__info.html',1,'Concurrency::streams::details']]],
  ['_5ffilestream_5fcallback',['_filestream_callback',['../class_concurrency_1_1streams_1_1details_1_1__filestream__callback.html',1,'Concurrency::streams::details']]],
  ['_5ffunctiontypetraits',['_FunctionTypeTraits',['../structpplx_1_1details_1_1___function_type_traits.html',1,'pplx::details']]],
  ['_5ffunctiontypetraits_3c_20_5ffunction_2c_20void_20_3e',['_FunctionTypeTraits&lt; _Function, void &gt;',['../structpplx_1_1details_1_1___function_type_traits_3_01___function_00_01void_01_4.html',1,'pplx::details']]],
  ['_5fhttp_5fclient_5fcommunicator',['_http_client_communicator',['../classweb_1_1http_1_1client_1_1details_1_1__http__client__communicator.html',1,'web::http::client::details']]],
  ['_5fhttp_5frequest',['_http_request',['../classweb_1_1http_1_1details_1_1__http__request.html',1,'web::http::details']]],
  ['_5fhttp_5fresponse',['_http_response',['../classweb_1_1http_1_1details_1_1__http__response.html',1,'web::http::details']]],
  ['_5fhttp_5fserver_5fcontext',['_http_server_context',['../classweb_1_1http_1_1details_1_1__http__server__context.html',1,'web::http::details']]],
  ['_5finit_5ffunc_5ftransformer',['_Init_func_transformer',['../classpplx_1_1___init__func__transformer.html',1,'pplx']]],
  ['_5finit_5ffunc_5ftransformer_3c_20void_20_3e',['_Init_func_transformer&lt; void &gt;',['../classpplx_1_1___init__func__transformer_3_01void_01_4.html',1,'pplx']]],
  ['_5finitfunctortypetraits',['_InitFunctorTypeTraits',['../structpplx_1_1details_1_1___init_functor_type_traits.html',1,'pplx::details']]],
  ['_5finitfunctortypetraits_3c_20t_2c_20t_20_3e',['_InitFunctorTypeTraits&lt; T, T &gt;',['../structpplx_1_1details_1_1___init_functor_type_traits_3_01_t_00_01_t_01_4.html',1,'pplx::details']]],
  ['_5finternal_5ftask_5foptions',['_Internal_task_options',['../structpplx_1_1details_1_1___internal__task__options.html',1,'pplx::details']]],
  ['_5finterruption_5fexception',['_Interruption_exception',['../classpplx_1_1details_1_1___interruption__exception.html',1,'pplx::details']]],
  ['_5fisiasyncinfo',['_IsIAsyncInfo',['../structpplx_1_1details_1_1___is_i_async_info.html',1,'pplx::details']]],
  ['_5fisunwrappedasyncselector',['_IsUnwrappedAsyncSelector',['../structpplx_1_1details_1_1___is_unwrapped_async_selector.html',1,'pplx::details']]],
  ['_5fisunwrappedasyncselector_3c_20_5ftypeselectornoasync_20_3e',['_IsUnwrappedAsyncSelector&lt; _TypeSelectorNoAsync &gt;',['../structpplx_1_1details_1_1___is_unwrapped_async_selector_3_01___type_selector_no_async_01_4.html',1,'pplx::details']]],
  ['_5fnormalizevoidtounittype',['_NormalizeVoidToUnitType',['../structpplx_1_1details_1_1___normalize_void_to_unit_type.html',1,'pplx::details']]],
  ['_5fnormalizevoidtounittype_3c_20void_20_3e',['_NormalizeVoidToUnitType&lt; void &gt;',['../structpplx_1_1details_1_1___normalize_void_to_unit_type_3_01void_01_4.html',1,'pplx::details']]],
  ['_5fnull',['_Null',['../classweb_1_1json_1_1details_1_1___null.html',1,'web::json::details']]],
  ['_5fnumber',['_Number',['../classweb_1_1json_1_1details_1_1___number.html',1,'web::json::details']]],
  ['_5fobject',['_Object',['../classweb_1_1json_1_1details_1_1___object.html',1,'web::json::details']]],
  ['_5fppltaskhandle',['_PPLTaskHandle',['../structpplx_1_1details_1_1___p_p_l_task_handle.html',1,'pplx::details']]],
  ['_5fppltaskhandle_3c_20_5freturntype_2c_20_5finitialtaskhandle_3c_20_5finternalreturntype_2c_20_5ffunction_2c_20_5ftypeselection_20_3e_2c_20details_3a_3a_5funrealizedchore_5ft_20_3e',['_PPLTaskHandle&lt; _ReturnType, _InitialTaskHandle&lt; _InternalReturnType, _Function, _TypeSelection &gt;, details::_UnrealizedChore_t &gt;',['../structpplx_1_1details_1_1___p_p_l_task_handle.html',1,'pplx::details']]],
  ['_5fppltaskhandle_3c_20details_3a_3a_5fnormalizevoidtounittype_3c_20_5fcontinuationreturntype_20_3e_3a_3a_5ftype_2c_20_5fcontinuationtaskhandle_3c_20_5finternalreturntype_2c_20_5fcontinuationreturntype_2c_20_5ffunction_2c_20_5fistaskbased_2c_20_5ftypeselection_20_3e_2c_20details_3a_3a_5fcontinuationtaskhandlebase_20_3e',['_PPLTaskHandle&lt; details::_NormalizeVoidToUnitType&lt; _ContinuationReturnType &gt;::_Type, _ContinuationTaskHandle&lt; _InternalReturnType, _ContinuationReturnType, _Function, _IsTaskBased, _TypeSelection &gt;, details::_ContinuationTaskHandleBase &gt;',['../structpplx_1_1details_1_1___p_p_l_task_handle.html',1,'pplx::details']]],
  ['_5frefcounter',['_RefCounter',['../classpplx_1_1details_1_1___ref_counter.html',1,'pplx::details']]],
  ['_5fresultholder',['_ResultHolder',['../structpplx_1_1details_1_1___result_holder.html',1,'pplx::details']]],
  ['_5fresultholder_3c_20_5fresulttype_20_3e',['_ResultHolder&lt; _ResultType &gt;',['../structpplx_1_1details_1_1___result_holder.html',1,'pplx::details']]],
  ['_5fresultholder_3c_20_5freturntype_20_3e',['_ResultHolder&lt; _ReturnType &gt;',['../structpplx_1_1details_1_1___result_holder.html',1,'pplx::details']]],
  ['_5fstring',['_String',['../classweb_1_1json_1_1details_1_1___string.html',1,'web::json::details']]],
  ['_5ftask_5fcompletion_5fevent_5fimpl',['_Task_completion_event_impl',['../structpplx_1_1details_1_1___task__completion__event__impl.html',1,'pplx::details']]],
  ['_5ftask_5fgenerator_5foversubscriber',['_Task_generator_oversubscriber',['../structpplx_1_1details_1_1___task__generator__oversubscriber.html',1,'pplx::details']]],
  ['_5ftask_5fimpl',['_Task_impl',['../structpplx_1_1details_1_1___task__impl.html',1,'pplx::details']]],
  ['_5ftask_5fimpl_5fbase',['_Task_impl_base',['../structpplx_1_1details_1_1___task__impl__base.html',1,'pplx::details']]],
  ['_5ftask_5fptr',['_Task_ptr',['../structpplx_1_1details_1_1___task__ptr.html',1,'pplx::details']]],
  ['_5ftask_5fptr_3c_20details_3a_3a_5fnormalizevoidtounittype_3c_20_5fcontinuationreturntype_20_3e_3a_3a_5ftype_20_3e',['_Task_ptr&lt; details::_NormalizeVoidToUnitType&lt; _ContinuationReturnType &gt;::_Type &gt;',['../structpplx_1_1details_1_1___task__ptr.html',1,'pplx::details']]],
  ['_5ftask_5fptr_3c_20details_3a_3a_5funit_5ftype_20_3e',['_Task_ptr&lt; details::_Unit_type &gt;',['../structpplx_1_1details_1_1___task__ptr.html',1,'pplx::details']]],
  ['_5ftaskcollectionimpl',['_TaskCollectionImpl',['../classpplx_1_1details_1_1___task_collection_impl.html',1,'pplx::details']]],
  ['_5ftaskcreationcallstack',['_TaskCreationCallstack',['../classpplx_1_1details_1_1___task_creation_callstack.html',1,'pplx::details']]],
  ['_5ftaskeventlogger',['_TaskEventLogger',['../structpplx_1_1details_1_1___task_event_logger.html',1,'pplx::details']]],
  ['_5ftaskprochandle',['_TaskProcHandle',['../structpplx_1_1details_1_1___task_proc_handle.html',1,'pplx::details']]],
  ['_5ftaskprocthunk',['_TaskProcThunk',['../structpplx_1_1details_1_1___task_proc_thunk.html',1,'pplx::details']]],
  ['_5ftasktypefromparam',['_TaskTypeFromParam',['../structpplx_1_1details_1_1___task_type_from_param.html',1,'pplx::details']]],
  ['_5ftasktypetraits',['_TaskTypeTraits',['../structpplx_1_1details_1_1___task_type_traits.html',1,'pplx::details']]],
  ['_5ftasktypetraits_3c_20void_20_3e',['_TaskTypeTraits&lt; void &gt;',['../structpplx_1_1details_1_1___task_type_traits_3_01void_01_4.html',1,'pplx::details']]],
  ['_5ftaskworkitemraiilogger',['_TaskWorkItemRAIILogger',['../structpplx_1_1details_1_1___task_work_item_r_a_i_i_logger.html',1,'pplx::details']]],
  ['_5ftype_5fparser_5fbase',['_type_parser_base',['../class_concurrency_1_1streams_1_1__type__parser__base.html',1,'Concurrency::streams']]],
  ['_5ftype_5fparser_5fintegral_5ftraits',['_type_parser_integral_traits',['../struct_concurrency_1_1streams_1_1__type__parser__integral__traits.html',1,'Concurrency::streams']]],
  ['_5ftypeselectorasyncaction',['_TypeSelectorAsyncAction',['../structpplx_1_1details_1_1___type_selector_async_action.html',1,'pplx::details']]],
  ['_5ftypeselectorasyncactionwithprogress',['_TypeSelectorAsyncActionWithProgress',['../structpplx_1_1details_1_1___type_selector_async_action_with_progress.html',1,'pplx::details']]],
  ['_5ftypeselectorasyncoperation',['_TypeSelectorAsyncOperation',['../structpplx_1_1details_1_1___type_selector_async_operation.html',1,'pplx::details']]],
  ['_5ftypeselectorasyncoperationortask',['_TypeSelectorAsyncOperationOrTask',['../structpplx_1_1details_1_1___type_selector_async_operation_or_task.html',1,'pplx::details']]],
  ['_5ftypeselectorasyncoperationwithprogress',['_TypeSelectorAsyncOperationWithProgress',['../structpplx_1_1details_1_1___type_selector_async_operation_with_progress.html',1,'pplx::details']]],
  ['_5ftypeselectorasynctask',['_TypeSelectorAsyncTask',['../structpplx_1_1details_1_1___type_selector_async_task.html',1,'pplx::details']]],
  ['_5ftypeselectornoasync',['_TypeSelectorNoAsync',['../structpplx_1_1details_1_1___type_selector_no_async.html',1,'pplx::details']]],
  ['_5funwraptasktype',['_UnwrapTaskType',['../structpplx_1_1details_1_1___unwrap_task_type.html',1,'pplx::details']]],
  ['_5funwraptasktype_3c_20task_3c_20_5fty_20_3e_20_3e',['_UnwrapTaskType&lt; task&lt; _Ty &gt; &gt;',['../structpplx_1_1details_1_1___unwrap_task_type_3_01task_3_01___ty_01_4_01_4.html',1,'pplx::details']]],
  ['_5fvalue',['_Value',['../classweb_1_1json_1_1details_1_1___value.html',1,'web::json::details']]]
];
