function(cpprest_find_curl)
  if(TARGET cpprestsdk_curl_internal)
    return()
  endif()

  if(NOT CURL_LIBRARY OR NOT CURL_INCLUDE_DIRS)
    find_package(CURL REQUIRED)
  endif()

  add_library(cpprestsdk_curl_internal INTERFACE)
  if(TARGET CURL::CURL)
    target_link_libraries(cpprestsdk_curl_internal INTERFACE CURL::CURL)
  else()
    target_link_libraries(cpprestsdk_curl_internal INTERFACE "$<BUILD_INTERFACE:${CURL_LIBRARY}>")
    target_include_directories(cpprestsdk_curl_internal INTERFACE "$<BUILD_INTERFACE:${CURL_INCLUDE_DIRS}>")
  endif()
endfunction()
